[package]
name = "compartment_rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "compartment_rs"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
log = "0.4.29"
pyo3 = "0.27.0"
